API/urls.py
from django.urls import path
from .views import MovieList, MovieDetail, SeriesList, SeriesDetail,MovieUploadView, SeriesUploadView
app_name='api'
urlpatterns = [
    path('movies/', MovieList.as_view(), name='movie-list'),
    path('movies/<int:pk>/', MovieDetail.as_view(), name='movie-detail'),
    path('series/', SeriesList.as_view(), name='series-list'),
    path('series/<int:pk>/', SeriesDetail.as_view(), name='series-detail'),
    path('movies/upload/', MovieUploadView.as_view(), name='movie-upload'),
    path('series/upload/', SeriesUploadView.as_view(), name='series-upload'),
]

adschlarship/urls.py
from django.contrib import admin
from django.urls import path  , include, re_path
from django.conf.urls.static import static
from . import settings
from django.conf.urls import url
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/', include('API.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
]
#if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                              document_root=settings.STATIC_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name='Vid'

urlpatterns = [
    path('', index, name='index'),
    path('<int:id>/', movie_detail, name='movie_detail'),
    path('video/<int:id>', stream_video, name='stream_video'),
    path('series', series_list, name='series_list'),
    path('kdrama', Kdrama, name='Kdrama'),
    path('Anime', Anime, name='Anime'),
    path('Animation', Animation, name='Animation'),
    path('series/<int:series_id>/', series_detail, name='series_detail'),
    path('episode/<int:episode_id>/download/', episode_download, name='episode_download'),
    path('episodes/<int:id>/stream/', episode_stream, name='episode_stream'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Anime Template">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Watch|Box</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="/">
                            <p><span style="font-size: xx-large;color: #ffffff;"><b> Watc</b></span><span style="font-size: xx-large;color: #f44336;"><b>h|Box</b></span> </p>
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li class="active"><a href="/">Movies</a></li>
                                <li><a href="/series">Series</a></li>
                                <li><a href="/Anime">Anime</a></li>
                                <li><a href="/Animation">Animation</a></li>
                                <li><a href="/Kdrama">Kdrama</a></li>
                                <li><a>Others<span class="arrow_carrot-down"></span></a>
                                    <ul class="dropdown">
                                        <li><a href="">{{ i.title }}</a></li>
                                        <li><a href="">{{ i.title }}</a></li>
                                        <li><a href="">{{ i.title }}</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <a href="#" class="search-switch"><span class="icon_search"></span></a>
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End 
	{% include 'messages.html' %}-->
	{% block body %}
	{% endblock %}

<!-- Footer Section Begin -->
<footer class="footer">
    <div class="page-up">
        <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="footer__logo">
                    <a href="/"><img src="img/logo.png" alt=""></a>
                    <p><span style="font-size: xx-large;color: #ffffff;"><b> Watc</b></span><span style="font-size: xx-large;color: #f44336;"><b>h|Box</b></span> </p>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="footer__nav">
                    <ul>
                        <li class="active"><a href="/">Movies</a></li>
                        <li><a href="/Anime">Anime</a></li>
                        <li><a href="/Animation">Animation</a></li>
                        <li><a href="/Kdrama">Kdrama</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3">
                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved <i class="fa fa-heart" aria-hidden="true"></i> by <a href="" target="_blank"><span style="color: #ffffff;"><b> Watc</b></span><span style="color: #f44336;"><b>h|Box</b></span> </a>
                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>

              </div>
          </div>
      </div>
  </footer>
  <!-- Footer Section End -->

  <!-- Search model Begin -->
  <div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch"><i class="icon_close"></i></div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search model end -->

<!-- Js Plugins -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/player.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


</body>

</html>

templates/detail.html
{% extends 'base.html' %}
{% block body %}

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="/"><i class="fa fa-home"></i> Home</a>
                        <span>{{series.title}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Anime Section Begin -->
    <section class="anime-details spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="anime__video__player">
                        <video id="player" playsinline controls data-poster="{{series.image.url}}" >
                            <!-- Captions are optional -->
                            <track kind="captions" label="English captions" src="#" srclang="en" default />
                        </video>
                    </div>
                    <div class="anime__details__episodes">
                        <div class="section-title">
                            <h5>Episodes</h5>
                        </div>
                        {% for i in episodes %}
                        <a href="{% url 'Vid:episode_download' i.id %}"><i class="fa fa-download"></i>   Download  Ep {{forloop.counter}}</a>

                        <button class="site-btn" onclick="streamEpisode(this)" id="stream-button" data-episode-id="{{forloop.counter}}">Watch  Ep {{forloop.counter}} Online</button>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Anime Section End -->
    <script>
        const videoPlayer = document.getElementById('player');

function streamEpisode(button) {
  const episodeId = button.getAttribute('data-episode-id');
  const episodeUrl = `/episodes/${episodeId}/stream/`;
  videoPlayer.src = episodeUrl;
}
    </script>
    {% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}
    <!-- Hero Section Begin -->
    <section class="hero">
        <div class="container">
            <div class="hero__slider owl-carousel">
                <div class="hero__items set-bg" data-setbg="static/img/hero/hero-1.jpg">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="hero__text">
                                <div class="label">Adventure</div>
                                <h2>Fate / Stay Night: Unlimited Blade Works</h2>
                                <p>After 30 days of travel across the world...</p>
                                <a href="#"><span>Watch Now</span> <i class="fa fa-angle-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="hero__items set-bg" data-setbg="static/img/hero/hero-1.jpg">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="hero__text">
                                <div class="label">Adventure</div>
                                <h2>Fate / Stay Night: Unlimited Blade Works</h2>
                                <p>After 30 days of travel across the world...</p>
                                <a href="#"><span>Watch Now</span> <i class="fa fa-angle-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="hero__items set-bg" data-setbg="static/img/hero/hero-1.jpg">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="hero__text">
                                <div class="label">Adventure</div>
                                <h2>Fate / Stay Night: Unlimited Blade Works</h2>
                                <p>After 30 days of travel across the world...</p>
                                <a href="#"><span>Watch Now</span> <i class="fa fa-angle-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

    <!-- Product Section Begin -->
    <section class="product spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="trending__product">
                        <div class="row">
                            {% for i in movies %}
                            <div class="col-lg-4 col-md-6 col-sm-6">
                                <div class="product__item">
                                    <div class="product__item__pic set-bg" data-setbg="{{i.image.url}}">
                                        <div class="ep">Details</div>
                                        {% if i.file %}
                                        <div class="comment" ><a href="{% url 'Vid:movie_detail' i.id %}"><i class="fa fa-play"></i>  Watch Live</a></div>
                                        <div class="view"><a href="{{ i.file.url }}" download="{{ i.file.url }}"><i class="fa fa-download"></i>  Download</div></a>
                                        {% else %}
                                        <div class="view"><a href="{% url 'Vid:series_detail' i.id %}"><i class="fa fa-eye"></i>View</div></a>
                                        {% endif %}  
                                    </div>
                                    <div class="product__item__text">
                                        <ul>
                                            {% if i.is_trending == True %}
                                            <li>Trending</li>
                                            {% elif i.is_thriller == True %}
                                            <li>Thriller</li>
                                            {% elif i.is_action == True %}
                                            <li>Action</li>
                                            {% elif i.is_kdrama == True %}
                                            <li>Kdrama</li>
                                            {% elif i.is_anime == True %}
                                            <li>AAnime</li>
                                            {% elif i.is_horror == True %}
                                            <li>Horror</li>
                                            {% elif i.is_animation == True %}
                                            <li>Animation</li>
                                            {% endif %}
                                        </ul>
                                        {% if i.file %}
                                        <h5><a href="#">{{ i.title }}</a></h5>
                                        {% else %}
                                        <h5><a href="{% url 'Vid:series_detail' i.id %}">{{ i.title }}</a></h5>
                                        {% endif %} 
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
</section>
<!-- Product Section End -->

{% endblock %}

templates/messages.html
{% if messages %}

	{% for message in messages %}
	<script type="text/javascript">
		
			alert("{{message}}");
	</script>
	{% endfor %}

{% endif %}

templates/watchmv.html
{% extends 'base.html' %}
{% block body %}

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="/"><i class="fa fa-home"></i> Home</a>
                        <a href="./categories.html">{{i.types.name}}</a>
                        <a href="#">Romance</a>
                        <span>{{i.title}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Anime Section Begin -->
    <section class="anime-details spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="anime__video__player">
                        <video id="player" playsinline controls data-poster="{{i.image.url}}">
                            <!-- Captions are optional -->
                            <source src="{% url 'Vid:stream_video' i.id %}" type="video/mp4">
                            <track kind="captions" label="English captions" src="#" srclang="en" default />
                        </video>
                    </div>
                    <div class="anime__details__episodes">
                        <div class="section-title">
                            <h5>Options Availlable</h5>
                        </div>

                        <a href="{% url 'Vid:episode_download' i.id %}"><i class="fa fa-download"></i>   Download</a>

                        <button class="site-btn" onclick="playVideo()" id="stream-button" data-episode-id="">  Watch Online</button>


                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        var video = document.getElementById("player");
        
        // Play the video
        function playVideo() {
          video.play();
        }
        
        // Pause the video
        function pauseVideo() {
          video.pause();
        }
        </script>
    {% endblock %}